SET local check_function_bodies = off;

CREATE TABLE "public"."acquisition_profile" (
  "id"             bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "niche"          text                     NOT NULL,
  "countries"      text                     NOT NULL,
  "who_exactly"    text,
  "what_we_sell"   text,
  "price"          text,
  "call_days"      text,
  "past_work_what" text,
  "past_work_why"  text,
  "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "acquisition_profile_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."acquisition_profile"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."ai_usage_monthly" (
  "month"       text   NOT NULL,
  "tokens_used" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "ai_usage_monthly_pkey" PRIMARY KEY (month)
);

ALTER TABLE "public"."ai_usage_monthly"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."brand_assets" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "client_id"  bigint,
  "title"      text,
  "type"       text,
  "added_at"   timestamp with time zone DEFAULT now(),
  CONSTRAINT "brand_assets_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."brand_assets"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."clients" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"         text,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "project_name" text,
  "initials"     text,
  "color"        text,
  "avatar_url"   text,
  "email"        text,
  "phone"        text,
  "status"       text                     DEFAULT 'active'::text,
  "owner"        text,
  "start_date"   date,
  "due_date"     date,
  "phases"       jsonb                    DEFAULT '[]'::jsonb,
  "workshop"     jsonb,
  "total_amount" numeric,
  CONSTRAINT "clients_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."clients"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."deals" (
  "id"              bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "title"           text                     NOT NULL,
  "value"           numeric,
  "currency"        text                     NOT NULL DEFAULT 'USD'::text,
  "stage"           text                     NOT NULL DEFAULT 'new'::text,
  "priority"        text                     NOT NULL DEFAULT 'medium'::text,
  "contact_id"      bigint,
  "contact_name"    text,
  "contact_country" text,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "deals_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."deals"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."document_comments" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."document comments_id_seq") NOT NULL,
  "document_id" bigint,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "author_name" text,
  "author_type" text,
  "text"        text,
  "page_label"  text,
  CONSTRAINT "document comments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."document_comments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."documents" (
  "id"                           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id"                    bigint,
  "created_at"                   timestamp with time zone NOT NULL DEFAULT now(),
  "title"                        text,
  "type"                         text,
  "status"                       text,
  "meta"                         text,
  "url"                          text,
  "updated_at"                   timestamp with time zone DEFAULT now(),
  "testimonial_text"             text,
  "testimonial_author_name"      text,
  "testimonial_author_type"      text,
  "testimonial_created_at"       timestamp with time zone,
  "agency_signature_data"        text,
  "agency_signature_author_name" text,
  "agency_signature_created_at"  timestamp with time zone,
  "client_signature_data"        text,
  "client_signature_author_name" text,
  "client_signature_created_at"  timestamp with time zone,
  "invoice_number"               text,
  "billed_to_name"               text,
  "issued_date"                  date,
  "due_date"                     date,
  "amount"                       numeric,
  "invoice_approved"             boolean,
  "stamp_layout"                 jsonb,
  "agency_signature_date_text"   text,
  "client_signature_date_text"   text,
  "unstamped_url"                text,
  CONSTRAINT "documents_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."documents"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."events" (
  "id"                     bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"             timestamp with time zone NOT NULL DEFAULT now(),
  "client_id"              bigint,
  "title"                  text,
  "date"                   date,
  "time"                   text,
  "notes"                  text,
  "content_type"           text,
  "duration"               text,
  "amount"                 integer,
  "file_url"               text,
  "file_name"              text,
  "file_kind"              text,
  "calendly_uri"           text,
  "category"               text,
  "color"                  text,
  "tags"                   jsonb,
  "with_client_id"         bigint,
  "with_client_name"       text,
  "linked_client_event_id" bigint,
  CONSTRAINT "events_calendly_uri_key" UNIQUE (calendly_uri),
  CONSTRAINT "events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."leads" (
  "id"                  bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "company_name"        text                     NOT NULL,
  "website"             text,
  "platform"            text,
  "contact_name"        text,
  "contact_email"       text,
  "country"             text,
  "why_fits"            text,
  "noticed_note"        text,
  "status"              text                     NOT NULL DEFAULT 'new'::text,
  "owner"               text                     NOT NULL,
  "not_now_until"       date,
  "converted_client_id" bigint,
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "source"              text,
  CONSTRAINT "leads_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."leads"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."library_files" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "folder_id"  bigint,
  "title"      text,
  "file_type"  text,
  "file_name"  text,
  "url"        text,
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "library_files_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."library_files"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."library_folders" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "client_id"  bigint,
  "name"       text,
  CONSTRAINT "library_folders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."library_folders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."mcp_auth_codes" (
  "code"                   text                     NOT NULL,
  "client_id"              text                     NOT NULL,
  "user_id"                uuid                     NOT NULL,
  "code_challenge"         text                     NOT NULL,
  "redirect_uri"           text                     NOT NULL,
  "scope"                  text,
  "resource"               text,
  "supabase_refresh_token" text                     NOT NULL,
  "expires_at"             timestamp with time zone NOT NULL,
  "created_at"             timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mcp_auth_codes_pkey" PRIMARY KEY (code)
);

ALTER TABLE "public"."mcp_auth_codes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."mcp_connections" (
  "id"                      uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "client_id"               text                     NOT NULL,
  "user_id"                 uuid                     NOT NULL,
  "access_token_hash"       text                     NOT NULL,
  "refresh_token_hash"      text                     NOT NULL,
  "supabase_refresh_token"  text                     NOT NULL,
  "scope"                   text,
  "resource"                text,
  "access_token_expires_at" timestamp with time zone NOT NULL,
  "created_at"              timestamp with time zone NOT NULL DEFAULT now(),
  "last_used_at"            timestamp with time zone,
  CONSTRAINT "mcp_connections_access_token_hash_key" UNIQUE (access_token_hash),
  CONSTRAINT "mcp_connections_pkey" PRIMARY KEY (id),
  CONSTRAINT "mcp_connections_refresh_token_hash_key" UNIQUE (refresh_token_hash)
);

ALTER TABLE "public"."mcp_connections"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."mcp_oauth_clients" (
  "client_id"                  text                     NOT NULL,
  "client_secret"              text,
  "client_id_issued_at"        bigint                   NOT NULL,
  "client_secret_expires_at"   bigint,
  "redirect_uris"              jsonb                    NOT NULL,
  "client_name"                text,
  "client_uri"                 text,
  "logo_uri"                   text,
  "scope"                      text,
  "contacts"                   jsonb,
  "tos_uri"                    text,
  "policy_uri"                 text,
  "jwks_uri"                   text,
  "jwks"                       jsonb,
  "software_id"                text,
  "software_version"           text,
  "grant_types"                jsonb,
  "response_types"             jsonb,
  "token_endpoint_auth_method" text,
  "created_at"                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mcp_oauth_clients_pkey" PRIMARY KEY (client_id)
);

ALTER TABLE "public"."mcp_oauth_clients"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "role"       text,
  "client_id"  bigint,
  "full_name"  text,
  CONSTRAINT "profliles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sequence_steps" (
  "id"          bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "lead_id"     bigint                   NOT NULL,
  "step_type"   text                     NOT NULL,
  "due_date"    date                     NOT NULL,
  "done"        boolean                  NOT NULL DEFAULT false,
  "done_at"     timestamp with time zone,
  "order_index" integer                  NOT NULL,
  CONSTRAINT "sequence_steps_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sequence_steps"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."suppressed_contacts" (
  "email"         text                     NOT NULL,
  "company_name"  text,
  "suppressed_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "suppressed_contacts_pkey" PRIMARY KEY (email)
);

ALTER TABLE "public"."suppressed_contacts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tasks" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "done"       boolean                  NOT NULL DEFAULT false,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "client_id"  bigint,
  "title"      text,
  "due_date"   date,
  "assignee"   text,
  "start_date" date,
  CONSTRAINT "tasks_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tasks"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."touches" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "lead_id"    bigint                   NOT NULL,
  "kind"       text                     NOT NULL,
  "note"       text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "touches_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."touches"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."updates" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "client_id"   bigint,
  "text"        text,
  "date"        timestamp with time zone,
  "author"      text,
  "author_type" text,
  "doc_id"      bigint,
  "doc_title"   text,
  CONSTRAINT "updates_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."updates"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  if new.raw_user_meta_data ? 'role' then
    insert into public.profiles (id, role, client_id, full_name)
    values (
      new.id,
      new.raw_user_meta_data ->> 'role',
      nullif(new.raw_user_meta_data ->> 'client_id', '')::bigint,
      new.raw_user_meta_data ->> 'full_name'
    )
    on conflict (id) do update
      set role = excluded.role,
          client_id = excluded.client_id,
          full_name = excluded.full_name
      where public.profiles.role <> 'agency';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.is_agency()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'agency'
  );
$function$;

CREATE OR REPLACE FUNCTION public.link_client_invite (
  target_email     text,
  target_role      text,
  target_client_id bigint,
  target_full_name text
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  target_id uuid;
begin
  if not public.is_agency() then
    raise exception 'not authorized';
  end if;

  select id into target_id from auth.users where lower(email) = lower(target_email);
  if target_id is null then
    return;
  end if;

  insert into public.profiles (id, role, client_id, full_name)
  values (target_id, target_role, target_client_id, target_full_name)
  on conflict (id) do update
    set role = excluded.role,
        client_id = excluded.client_id,
        full_name = excluded.full_name
    where public.profiles.role <> 'agency';
end;
$function$;

CREATE OR REPLACE FUNCTION public.my_client_id()
  RETURNS bigint
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  select client_id from public.profiles where id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

ALTER TABLE "public"."brand_assets"
  ADD CONSTRAINT "brand_assets_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."documents"
  ADD CONSTRAINT "documents_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."document_comments"
  ADD CONSTRAINT "document comments_document_id_fkey" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE;

ALTER TABLE "public"."events"
  ADD CONSTRAINT "events_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."events"
  ADD CONSTRAINT "events_linked_client_event_id_fkey" FOREIGN KEY (linked_client_event_id) REFERENCES public.events(id) ON DELETE SET NULL;

ALTER TABLE "public"."events"
  ADD CONSTRAINT "events_with_client_id_fkey" FOREIGN KEY (with_client_id) REFERENCES public.clients(id) ON DELETE SET NULL;

ALTER TABLE "public"."leads"
  ADD CONSTRAINT "leads_converted_client_id_fkey" FOREIGN KEY (converted_client_id) REFERENCES public.clients(id) ON DELETE SET NULL;

ALTER TABLE "public"."deals"
  ADD CONSTRAINT "deals_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.leads(id) ON DELETE SET NULL;

ALTER TABLE "public"."library_folders"
  ADD CONSTRAINT "library_folders_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."library_files"
  ADD CONSTRAINT "library_files_folder_id_fkey" FOREIGN KEY (folder_id) REFERENCES public.library_folders(id) ON DELETE CASCADE;

ALTER TABLE "public"."mcp_auth_codes"
  ADD CONSTRAINT "mcp_auth_codes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."mcp_connections"
  ADD CONSTRAINT "mcp_connections_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."mcp_auth_codes"
  ADD CONSTRAINT "mcp_auth_codes_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.mcp_oauth_clients(client_id) ON DELETE CASCADE;

ALTER TABLE "public"."mcp_connections"
  ADD CONSTRAINT "mcp_connections_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.mcp_oauth_clients(client_id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profliles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id);

ALTER TABLE "public"."sequence_steps"
  ADD CONSTRAINT "sequence_steps_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;

ALTER TABLE "public"."tasks"
  ADD CONSTRAINT "tasks_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."touches"
  ADD CONSTRAINT "touches_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE;

ALTER TABLE "public"."updates"
  ADD CONSTRAINT "updates_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;

ALTER TABLE "public"."updates"
  ADD CONSTRAINT "updates_doc_id_fkey" FOREIGN KEY (doc_id) REFERENCES public.documents(id) ON DELETE CASCADE;

CREATE INDEX deals_contact_id_idx ON public.deals USING btree (contact_id);

CREATE INDEX deals_stage_idx ON public.deals USING btree (stage);

CREATE INDEX events_client_id_idx ON public.events USING btree (client_id);

CREATE INDEX idx_brand_assets_client_id ON public.brand_assets USING btree (client_id);

CREATE INDEX idx_document_comments_document_id ON public.document_comments USING btree (document_id);

CREATE INDEX idx_documents_client_id ON public.documents USING btree (client_id);

CREATE INDEX idx_events_client_id ON public.events USING btree (client_id);

CREATE INDEX idx_library_files_folder_id ON public.library_files USING btree (folder_id);

CREATE INDEX idx_library_folders_client_id ON public.library_folders USING btree (client_id);

CREATE INDEX idx_profiles_client_id ON public.profiles USING btree (client_id);

CREATE INDEX idx_tasks_client_id ON public.tasks USING btree (client_id);

CREATE INDEX idx_updates_client_id ON public.updates USING btree (client_id);

CREATE INDEX leads_status_idx ON public.leads USING btree (status);

CREATE INDEX mcp_auth_codes_expires_at_idx ON public.mcp_auth_codes USING btree (expires_at);

CREATE INDEX mcp_connections_user_id_idx ON public.mcp_connections USING btree (user_id);

CREATE INDEX sequence_steps_due_date_idx ON public.sequence_steps USING btree (due_date)
  WHERE (done = false);

CREATE INDEX sequence_steps_lead_id_idx ON public.sequence_steps USING btree (lead_id);

CREATE INDEX touches_lead_id_idx ON public.touches USING btree (lead_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE POLICY "Agency can manage the acquisition profile" ON "public"."acquisition_profile"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."brand_assets"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."brand_assets"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "Agency full access" ON "public"."clients"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."clients"
  FOR SELECT
  TO PUBLIC
  USING ((id = public.my_client_id()));

CREATE POLICY "client_update_own" ON "public"."clients"
  FOR UPDATE
  TO PUBLIC
  USING ((id = public.my_client_id()))
  WITH CHECK ((id = public.my_client_id()));

CREATE POLICY "Agency can manage deals" ON "public"."deals"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."document_comments"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_insert_own" ON "public"."document_comments"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.documents d
  WHERE ((d.id = document_comments.document_id) AND (d.client_id = public.my_client_id())))));

CREATE POLICY "client_select_own" ON "public"."document_comments"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.documents d
  WHERE ((d.id = document_comments.document_id) AND (d.client_id = public.my_client_id())))));

CREATE POLICY "Agency full access" ON "public"."documents"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."documents"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "client_update_own" ON "public"."documents"
  FOR UPDATE
  TO PUBLIC
  USING ((client_id = public.my_client_id()))
  WITH CHECK ((client_id = public.my_client_id()));

CREATE POLICY "Agency can manage all events" ON "public"."events"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."events"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "Clients can manage their own events" ON "public"."events"
  FOR ALL
  TO PUBLIC
  USING (((client_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'client'::text) AND (profiles.client_id = events.client_id))))))
  WITH CHECK (((client_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'client'::text) AND (profiles.client_id = events.client_id))))));

CREATE POLICY "client_select_own" ON "public"."events"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "Agency can manage leads" ON "public"."leads"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."library_files"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."library_files"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.library_folders f
  WHERE ((f.id = library_files.folder_id) AND (f.client_id = public.my_client_id())))));

CREATE POLICY "Agency full access" ON "public"."library_folders"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."library_folders"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "Agency full access" ON "public"."profiles"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "Read own profile" ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING ((auth.uid() = id));

CREATE POLICY "self_select" ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING ((id = auth.uid()));

CREATE POLICY "Agency can manage sequence steps" ON "public"."sequence_steps"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency can read suppressed contacts" ON "public"."suppressed_contacts"
  FOR SELECT
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency can write suppressed contacts" ON "public"."suppressed_contacts"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."tasks"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_select_own" ON "public"."tasks"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "client_update_own" ON "public"."tasks"
  FOR UPDATE
  TO PUBLIC
  USING ((client_id = public.my_client_id()))
  WITH CHECK ((client_id = public.my_client_id()));

CREATE POLICY "Agency can manage touches" ON "public"."touches"
  FOR ALL
  TO PUBLIC
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'agency'::text)))));

CREATE POLICY "Agency full access" ON "public"."updates"
  FOR ALL
  TO PUBLIC
  USING (public.is_agency())
  WITH CHECK (public.is_agency());

CREATE POLICY "client_insert_own" ON "public"."updates"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((client_id = public.my_client_id()));

CREATE POLICY "client_select_own" ON "public"."updates"
  FOR SELECT
  TO PUBLIC
  USING ((client_id = public.my_client_id()));

CREATE POLICY "agency_full_access_documents_bucket" ON "storage"."objects"
  FOR ALL
  TO PUBLIC
  USING (((bucket_id = 'documents'::text) AND public.is_agency()))
  WITH CHECK (((bucket_id = 'documents'::text) AND public.is_agency()));

CREATE POLICY "client_read_own_documents_bucket" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'documents'::text) AND ((storage.foldername(name))[1] = ( SELECT (profiles.client_id)::text AS client_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid())))));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."document_comments";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."documents";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."events";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."tasks";

ALTER PUBLICATION "supabase_realtime" ADD TABLE "public"."updates";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."is_agency"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."is_agency"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_agency"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."is_agency"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."link_client_invite"(text, text, bigint, text) TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."link_client_invite"(text, text, bigint, text) FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."link_client_invite"(text, text, bigint, text) TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."link_client_invite"(text, text, bigint, text) TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."my_client_id"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."my_client_id"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."my_client_id"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."my_client_id"() TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "service_role";

REVOKE ALL ON SEQUENCE "public"."document comments_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."document comments_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."document comments_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."document comments_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."document comments_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."document comments_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."document comments_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."document comments_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."acquisition_profile_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."acquisition_profile_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."acquisition_profile_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."acquisition_profile_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."acquisition_profile_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."acquisition_profile_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."acquisition_profile_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."acquisition_profile_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."brand_assets_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."brand_assets_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."brand_assets_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."brand_assets_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."brand_assets_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."brand_assets_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."brand_assets_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."brand_assets_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."clients_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."clients_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."clients_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."clients_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."clients_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."clients_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."clients_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."clients_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."deals_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."deals_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."deals_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."deals_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."deals_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."deals_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."deals_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."deals_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."documents_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."documents_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."documents_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."documents_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."documents_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."documents_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."documents_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."documents_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."events_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."events_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."leads_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."leads_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."leads_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."leads_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."leads_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."leads_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."leads_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."leads_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."library_files_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_files_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."library_files_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_files_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."library_files_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_files_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."library_files_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_files_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."library_folders_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_folders_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."library_folders_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_folders_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."library_folders_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_folders_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."library_folders_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."library_folders_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."sequence_steps_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."sequence_steps_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."sequence_steps_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."sequence_steps_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."sequence_steps_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."sequence_steps_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."sequence_steps_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."sequence_steps_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."tasks_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tasks_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."tasks_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tasks_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."tasks_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tasks_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."tasks_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."tasks_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."touches_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."touches_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."touches_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."touches_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."touches_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."touches_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."touches_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."touches_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."updates_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."updates_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."updates_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."updates_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."updates_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."updates_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."updates_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."updates_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."acquisition_profile" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."acquisition_profile" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."acquisition_profile" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."acquisition_profile" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_usage_monthly" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."ai_usage_monthly" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_usage_monthly" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ai_usage_monthly" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."brand_assets" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."brand_assets" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."brand_assets" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."brand_assets" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."clients" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."clients" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."clients" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."clients" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."deals" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."deals" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."deals" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."deals" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."document_comments" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."document_comments" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."document_comments" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."document_comments" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."documents" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."documents" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."documents" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."documents" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."events" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leads" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."leads" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leads" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leads" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_files" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."library_files" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_files" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_files" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_folders" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."library_folders" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_folders" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."library_folders" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_auth_codes" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."mcp_auth_codes" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_auth_codes" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_auth_codes" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_connections" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."mcp_connections" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_connections" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_connections" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_oauth_clients" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."mcp_oauth_clients" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_oauth_clients" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mcp_oauth_clients" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."profiles" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sequence_steps" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."sequence_steps" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sequence_steps" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sequence_steps" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."suppressed_contacts" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."suppressed_contacts" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."suppressed_contacts" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."suppressed_contacts" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."tasks" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tasks" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."touches" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."touches" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."touches" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."touches" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."updates" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."updates" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."updates" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."updates" TO "service_role";

